In [2]:
import numpy as np

## Exercise 1

In [2]:
# create an array specifying values between -15 and 15 and square root each value
a = np.arange(-15,15).reshape(5,6)**2
a 

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

Question 1: Compute the maximum of each row

In [3]:
max_value = np.max(a, axis=1)
print(max_value)

[225  81   9  64 196]


Question 2: The mean of each column

In [6]:
mean_value = np.mean(a, axis=0)
print(mean_value)

[81. 76. 73. 72. 73. 76.]


Question 3: The position of the overall minimum

In [7]:
min_value = np.min(a)
print(min_value)

0


## Exercise 2

In [3]:
temp = np.loadtxt('http://www.geography.hunter.cuny.edu/~wenge/EDS2022F/data/NYCMet/CPannualT.csv',skiprows=2,delimiter=',')
temp

array([[2000. ,   31.3,   37.3,   47.2,   51. ,   63.5,   71.3,   72.3,
          72.7,   66. ,   57. ,   45.3,   31.1,   53.9],
       [2001. ,   33.6,   35.9,   39.6,   54.2,   63.8,   72.9,   73.2,
          78.7,   67.7,   58.5,   52.7,   44.1,   56.3],
       [2002. ,   39.9,   40.6,   44.1,   56.1,   60.7,   71.4,   78.8,
          77.7,   70.2,   55.2,   46. ,   36. ,   56.4],
       [2003. ,   27.5,   30.1,   43.1,   49.8,   58.7,   68.3,   75.8,
          76.7,   67.9,   55.1,   50. ,   37.6,   53.4],
       [2004. ,   24.7,   35. ,   43.5,   53.6,   65.2,   71.2,   74.5,
          74.2,   69.3,   56. ,   48.2,   38.4,   54.5],
       [2005. ,   31.3,   36.5,   39.4,   55.1,   58.9,   74. ,   77.5,
          79.7,   73.3,   57.9,   49.6,   35.3,   55.8],
       [2006. ,   40.9,   35.7,   43.1,   55.7,   63.1,   71. ,   77.9,
          75.8,   66.6,   56.2,   51.9,   43.6,   56.8],
       [2007. ,   37.5,   28.2,   42.2,   50.3,   65.2,   71.4,   75. ,
          74. ,   70.3,  

Question 1: Find out the mean, max, min standard deviation of monthly temperature for all 20 years:

In [17]:
max_temp = np.amax(temp, axis=0)
print(max_temp[1:13])

[40.9 42.  50.9 57.9 68.5 74.7 81.3 79.7 74.5 64.1 53.  50.8]


In [18]:
mean_temp = np.mean(temp, axis=0)
print(mean_temp[1:13])

[33.33333333 35.65714286 42.97142857 53.7        63.1047619  71.84761905
 77.32380952 76.2        69.55238095 58.04761905 48.13809524 38.75238095]


In [19]:
min_temp = np.min(temp, axis=0)
print(min_temp[1:13])

[24.7 23.9 37.7 49.5 58.7 67.5 72.3 72.7 66.  55.  43.9 31.1]


In [20]:
std_temp = np.std(temp, axis=0)
print(std_temp[1:13])

[4.36919229 4.40568587 3.64876272 2.33319727 2.48451896 1.66236179
 2.52301874 1.98182215 2.10070715 2.42263514 3.13391223 4.28859163]


Question 2: Find out the mean and standard deviation of monthly temperature for each month

Question 3: Find the years and months when monthly temperature greater > 80 degrees F

Question 4: Find the years and monthswhen monthly temperature less than < 32 degrees F